name: Test Action

on:
  #schedule:
  #  # There's no obvious way to run actions on new security advisories, so just run this
  #  # every two hours.
  #  - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  respond_to_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repo environment
        uses: ./.github/actions/setup-repo-env
      - name: Run respond_to_issues.py
        run: python respond_to_issues.py