name: Test Action

on:
  #schedule:
  #  # There's no obvious way to run actions on new security advisories, so just run this
  #  # every two hours.
  #  - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  respond_to_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run respond_to_issues.py
        run: python respond_to_issues.py