name: Run Tests

on:
  pull_request:
    paths:
      - '*.py'
      - '.github/**'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up repo environment
        uses: ./.github/actions/setup-repo-env

      - name: Run email script tests
        run: python3 email_about_issues_test.py

      - name: Run rotation extension tests
        run: python3 extend_rotation_test.py

      - name: Run pyright
        run: pyright *.py

      - name: Run mypy
        run: mypy . --explicit-package-bases
