name: Run Tests

on:
  pull_request:
    paths:
      - '**/*.py'
      - '.github/**'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up repo environment
        uses: ./.github/actions/setup-repo-env

      - name: Run email script tests
        run: python3 email-rotation/email_about_issues_test.py

      - name: Run rotation extension tests
        run: python3 email-rotation/extend_rotation_test.py

      - name: Run pyright
        run: pyright email-rotation/*.py

      - name: Run mypy
        run: mypy email-rotation/ --explicit-package-bases --strict

      - name: Run isort
        run: isort email-rotation/ --check-only

      - name: Run black
        run: black email-rotation/ --check
